name: go_riverpod_poc
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dio:
  flutter_dotenv: ^5.1.0
  flutter_riverpod:
  freezed_annotation:
  geocoding:
  go_router: 8.0.3
  json_annotation:
  shared_preferences: ^2.2.1
  onboarding_overlay: ^3.2.1
  logging: ^1.0.2
  riverpod_annotation:
  showcaseview: ^2.0.3
  stack_trace:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^2.0.1
  freezed:
  json_serializable:
  riverpod_generator:

flutter:
  uses-material-design: true
  assets:
    - .env


